# TThis is the Kamaji Jekyll configuration file

plugins:
- jekyll-remote-theme

title: Kamaji Docs
description: Documentation page for Kamaji, the Illinois Space Society's Hardware-in-the-loop testing software.

markdown: GFM