version: '3'
services:
  web:
    build:
      context: ./Central-Server/hilsim-web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./Central-Server/hilsim-web/src:/src/hilsim-webapp/src
      - /Central-Server/hilsim-web/node_modules/
  api:
    build:
      context: ./Central-Server/API
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    environment:
      - PORT=443
    volumes:
      - ./Central-Server/API:/src/api
  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
