version: '3'
services:
  web:
    build:
      context: ./Central-Server/hilsim-web
      dockerfile: ./Dockerfile.prod
    ports:
      - "8080:8080"
  api:
    build:
      context: ./Central-Server/API
      dockerfile: ./Dockerfile.prod
    ports:
      - "443:443"
    environment:
      - PORT=443
      - DB_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - ./Central-Server/API:/src/api
    secrets:
      - db_password

  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# Ask someone responsible for the secrets folder
secrets:
  db_password:
    file: ./secrets/db_password.txt
