version: '3'
services:
  web:
    build:
      context: ./Central-Server/hilsim-web
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./Central-Server/hilsim-web/src:/src/hilsim-webapp/src
      - /Central-Server/hilsim-web/node_modules/

  api:
    build:
      context: ./Central-Server/API
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
      - "5001:5001"
    environment:
      - PORT=443
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=db
    volumes:
      - ./Central-Server/API:/src/api
    secrets:
      - db_password

  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  adminer:
    image: adminer
    restart: always

# Ask someone responsible for the secrets folder
secrets:
  db_password:
    file: ./secrets/db_password.txt
