# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_servers.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc_servers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_servers.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n\nWorkerInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\"1\n\tJobPacket\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61rtifact_url\x18\x02 \x01(\t2q\n\x0eManagerService\x12\x30\n\tSubscribe\x12\x0b.WorkerInfo\x1a\x16.google.protobuf.Empty\x12-\n\x07SendJob\x12\n.JobPacket\x1a\x16.google.protobuf.Empty2}\n\x0fTestRackService\x12\x38\n\x11SubscribeToServer\x12\x0b.WorkerInfo\x1a\x16.google.protobuf.Empty\x12\x30\n\nExecuteJob\x12\n.JobPacket\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_servers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERINFO']._serialized_start=51
  _globals['_WORKERINFO']._serialized_end=95
  _globals['_JOBPACKET']._serialized_start=97
  _globals['_JOBPACKET']._serialized_end=146
  _globals['_MANAGERSERVICE']._serialized_start=148
  _globals['_MANAGERSERVICE']._serialized_end=261
  _globals['_TESTRACKSERVICE']._serialized_start=263
  _globals['_TESTRACKSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
