FROM python:3.8-slim-buster
WORKDIR /src/api
RUN apt-get update && apt-get install -y libpq-dev gcc
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 443
CMD ["python3", "main.py", "prod"]
